% Group 2: Raj Patel, Zachary Rouviere, Evan Waxman
% Experiement 9 Part 2
% 11/15/21
%
% Description:
%	This matlab script takes the csv files generated by main.m for each bit
%	postion and for each SBOX the script will find the max value from a set
%	of four bit postions to determine which bit we should be looking at for
%	each SBOX. This script will print out the SBOX the corresponding bit 
%	postion, the subkey value and the value of the bit postion.


%function  keyselection()
    csv_dir = "./Data"; %gets directory
    csv_files = dir(fullfile(csv_dir,'*.csv'));

    b = [5 27 15 21 32 12 22 7 4 29 11 19 8 14 25 3 26 20 10 1 24 16 30 6 13 28 2 18 9 17 23 31]; %bit posistion for each SBOX
    SUBBOXRND = 9;
    
    
    for bit = 1: 4: length(b)
        T = zeros(4,3); % Zero matrix for finding the max value
        SUBBOXRND = SUBBOXRND-1; % mointor the SBOX #
        
        % loads data in (value and Subkey) and saves it to table. Adds the
        % bit position to row in table
        data_files = strcat(csv_files(1).folder,'\',string(b(bit)),'.csv');
        T(1,1:2) = csvread(data_files);
        T(1,3)=b(bit);
        
        % On next row of table loads data in (value and Subkey) and 
        %saves it to table. Adds the bit position to row in table
        data_files = strcat(csv_files(1).folder,'\',string(b(bit+1)),'.csv');
        T(2,1:2) = csvread(data_files);
        T(2,3)=b(bit+1);
        
        % On next row of table loads data in (value and Subkey) and 
        %saves it to table. Adds the bit position to row in table
        data_files = strcat(csv_files(1).folder,'\',string(b(bit+2)),'.csv');
        T(3,1:2) = csvread(data_files);
        T(3,3)=b(bit+2);
        
         % On next row of table loads data in (value and Subkey) and 
        %saves it to table. Adds the bit position to row in table
        data_files = strcat(csv_files(1).folder,'\',string(b(bit+3)),'.csv');
        T(4,1:2) = csvread(data_files);
        T(4,3)=b(bit+3);
        
        % Finds the max value for specific SBOX
        [value,row]=max(T(:,2));
        SBOXbit= T(row,3);
        SUBKEY = T(row,1);
        fprintf('SBOX%d Bit Position: %d and Subkey: %d and Value: %d \n',SUBBOXRND, SBOXbit,SUBKEY, value);
    end

%end

